---
version: 1.8.6.5
slug: ezddns
name: EZ DDNS
description: >
  Easy Cloudflare DDNS updates for IPv6 and IPv4
url: https://github.com/TKtheDEV/EZDDNS-HomeAssistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
init: false

options:
  zoneId: null
  apiToken: null
  hostfqdn: null
  v4Enabled: false
  prefixLength: 56
  refresh: 300
  dnsttl: 1
  proxied: false
  legacyMode: false
  customEnabled: false
  customRecords:
#   - AAAAcustom.example.com,AAAA,56:0123:45ff:fe67:89ab
#   - AAAA.example.com,AAAA
#   - A.example.com,A

schema:
  zoneId: str?
  apiToken: password
  hostfqdn: str?
  v4Enabled: bool
  prefixLength: list(48|52|56|60|64)
  refresh: "int(60,)"
  dnsttl: "int(1,86400)"
  proxied: bool
  legacyMode: bool
  customEnabled: bool
  customRecords:
    - str?
